/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 83bad730d24fec2d56c1539408838633)
interface __BaseEnv_Env {
	TELEGRAM_KV: KVNamespace;
	ENRICHMENT_USAGE: KVNamespace;
	DB: D1Database;
	USAGE_ANALYTICS: AnalyticsEngineDataset;
	LINK_QUEUE: Queue;
	X_RECONCILE_QUEUE: Queue;
	SYNC_RATE_LIMITER: RateLimit;
	METADATA_RATE_LIMITER: RateLimit;
	AI: Ai;
	ASSETS: Fetcher;
	EMAIL_FROM: "Cloudstash Staging <noreply@cloudstash.dev>" | "Cloudstash <noreply@cloudstash.dev>";
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	EXTENSION_ID_ALLOWLIST: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	OPENROUTER_API_KEY: string;
	RESEND_API_KEY: string;
	X_CLIENT_ID: string;
	X_CLIENT_SECRET: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_WEBHOOK_SECRET: string;
	STRIPE_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_PRICE_PLUS: string;
	STRIPE_PRICE_PLUS_YEARLY: string;
	STRIPE_PRICE_PRO: string;
	STRIPE_PRICE_PRO_YEARLY: string;
	CF_ACCOUNT_ID: string;
	CF_ANALYTICS_TOKEN: string;
	SYNC_BACKEND_DO: DurableObjectNamespace<import("./src/cf-worker/index").SyncBackendDO>;
	LIBRARY_DO: DurableObjectNamespace<import("./src/cf-worker/index").LibraryDO>;
	LINK_PROCESSOR_DO: DurableObjectNamespace<import("./src/cf-worker/index").LibraryDO>;
	Chat: DurableObjectNamespace<import("./src/cf-worker/index").ChatAgentDO>;
	X_BOOKMARK_SYNC_DO: DurableObjectNamespace<import("./src/cf-worker/index").XBookmarkSyncDO>;
	ACCOUNT_DELETION: Workflow<Parameters<import("./src/cf-worker/index").AccountDeletionWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cf-worker/index");
		durableNamespaces: "SyncBackendDO" | "ChatAgentDO" | "XBookmarkSyncDO" | "LibraryDO";
	}
	interface StagingEnv {
		TELEGRAM_KV: KVNamespace;
		ENRICHMENT_USAGE: KVNamespace;
		DB: D1Database;
		USAGE_ANALYTICS: AnalyticsEngineDataset;
		LINK_QUEUE: Queue;
		X_RECONCILE_QUEUE: Queue;
		SYNC_RATE_LIMITER: RateLimit;
		METADATA_RATE_LIMITER: RateLimit;
		AI: Ai;
		ASSETS: Fetcher;
		EMAIL_FROM: "Cloudstash Staging <noreply@cloudstash.dev>";
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		EXTENSION_ID_ALLOWLIST: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		OPENROUTER_API_KEY: string;
		RESEND_API_KEY: string;
		X_CLIENT_ID: string;
		X_CLIENT_SECRET: string;
		TELEGRAM_BOT_TOKEN: string;
		TELEGRAM_WEBHOOK_SECRET: string;
		STRIPE_API_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		STRIPE_PRICE_PLUS: string;
		STRIPE_PRICE_PLUS_YEARLY: string;
		STRIPE_PRICE_PRO: string;
		STRIPE_PRICE_PRO_YEARLY: string;
		CF_ACCOUNT_ID: string;
		CF_ANALYTICS_TOKEN: string;
		SYNC_BACKEND_DO: DurableObjectNamespace<import("./src/cf-worker/index").SyncBackendDO>;
		LIBRARY_DO: DurableObjectNamespace<import("./src/cf-worker/index").LibraryDO>;
		LINK_PROCESSOR_DO: DurableObjectNamespace<import("./src/cf-worker/index").LibraryDO>;
		Chat: DurableObjectNamespace<import("./src/cf-worker/index").ChatAgentDO>;
		X_BOOKMARK_SYNC_DO: DurableObjectNamespace<import("./src/cf-worker/index").XBookmarkSyncDO>;
		ACCOUNT_DELETION: Workflow<Parameters<import("./src/cf-worker/index").AccountDeletionWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_FROM" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "EXTENSION_ID_ALLOWLIST" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "OPENROUTER_API_KEY" | "RESEND_API_KEY" | "X_CLIENT_ID" | "X_CLIENT_SECRET" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_WEBHOOK_SECRET" | "STRIPE_API_KEY" | "STRIPE_WEBHOOK_SECRET" | "STRIPE_PRICE_PLUS" | "STRIPE_PRICE_PLUS_YEARLY" | "STRIPE_PRICE_PRO" | "STRIPE_PRICE_PRO_YEARLY" | "CF_ACCOUNT_ID" | "CF_ANALYTICS_TOKEN">> {}
}
