/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: ce1598550635c9a59caa89fd51a77b89)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cf-worker/index");
		durableNamespaces: "SyncBackendDO" | "LinkProcessorDO" | "ChatAgentDO" | "XBookmarkSyncDO";
	}
	interface Env {
		TELEGRAM_KV: KVNamespace;
		ENRICHMENT_USAGE: KVNamespace;
		DB: D1Database;
		USAGE_ANALYTICS: AnalyticsEngineDataset;
		LINK_QUEUE: Queue;
		SYNC_RATE_LIMITER: RateLimit;
		AI: Ai;
		ASSETS: Fetcher;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		TELEGRAM_BOT_TOKEN: string;
		TELEGRAM_WEBHOOK_SECRET: string;
		RESEND_API_KEY: string;
		EMAIL_FROM: string;
		OPENROUTER_API_KEY: string;
		CF_ACCOUNT_ID: string;
		CF_ANALYTICS_TOKEN: string;
		X_CLIENT_ID: string;
		X_CLIENT_SECRET: string;
		STRIPE_API_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		STRIPE_PRICE_PLUS: string;
		STRIPE_PRICE_PRO: string;
		SYNC_BACKEND_DO: DurableObjectNamespace<import("./src/cf-worker/index").SyncBackendDO>;
		LINK_PROCESSOR_DO: DurableObjectNamespace<import("./src/cf-worker/index").LinkProcessorDO>;
		Chat: DurableObjectNamespace<import("./src/cf-worker/index").ChatAgentDO>;
		X_BOOKMARK_SYNC_DO: DurableObjectNamespace<import("./src/cf-worker/index").XBookmarkSyncDO>;
		ACCOUNT_DELETION: Workflow<Parameters<import("./src/cf-worker/index").AccountDeletionWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_WEBHOOK_SECRET" | "RESEND_API_KEY" | "EMAIL_FROM" | "OPENROUTER_API_KEY" | "CF_ACCOUNT_ID" | "CF_ANALYTICS_TOKEN" | "X_CLIENT_ID" | "X_CLIENT_SECRET" | "STRIPE_API_KEY" | "STRIPE_WEBHOOK_SECRET" | "STRIPE_PRICE_PLUS" | "STRIPE_PRICE_PRO">> {}
}
