/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 63cc717dc842c4761285ad5c7c9f2542)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cf-worker/index");
		durableNamespaces: "SyncBackendDO" | "LinkProcessorDO" | "ChatAgentDO";
	}
	interface Env {
		TELEGRAM_KV: KVNamespace;
		DB: D1Database;
		USAGE_ANALYTICS: AnalyticsEngineDataset;
		LINK_QUEUE: Queue;
		SYNC_RATE_LIMITER: RateLimit;
		AI: Ai;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		TELEGRAM_BOT_TOKEN: string;
		TELEGRAM_WEBHOOK_SECRET: string;
		RESEND_API_KEY: string;
		OPENROUTER_API_KEY: string;
		CF_ACCOUNT_ID: string;
		CF_ANALYTICS_TOKEN: string;
		LINK_PROCESSOR_URL: string;
		LINK_PROCESSOR_TOKEN: string;
		SYNC_BACKEND_DO: DurableObjectNamespace<import("./src/cf-worker/index").SyncBackendDO>;
		LINK_PROCESSOR_DO: DurableObjectNamespace<import("./src/cf-worker/index").LinkProcessorDO>;
		Chat: DurableObjectNamespace<import("./src/cf-worker/index").ChatAgentDO>;
	}
}
interface Env extends Cloudflare.Env {}
