import { createFileRoute } from "@tanstack/react-router";

import {
  LegalAddress,
  LegalArticle,
  LegalShell,
  LegalUpdated,
} from "@/components/landing/legal-shell";
import { SITE_URL } from "@/components/landing/seo-data";

export const Route = createFileRoute("/privacy")({
  ssr: true,
  head: () => ({
    meta: [
      { title: "Privacy Policy — Cloudstash" },
      {
        name: "description",
        content:
          "How Cloudstash handles your data: what we collect, what we don't, and how to delete everything.",
      },
      { name: "robots", content: "noindex, follow" },
    ],
    links: [{ rel: "canonical", href: `${SITE_URL}/privacy` }],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <LegalShell
      eyebrow="Legal"
      title="Privacy Policy"
      lead="What we collect, what we don't, and how you stay in control of your archive."
    >
      <LegalArticle>
        <LegalUpdated date="May 12, 2026" />
        <p>We made this short and tried to write it in English, not lawyer.</p>

        <section id="tldr">
          <h2>TL;DR</h2>
          <ul>
            <li>
              We store your account (email and name from Google), the links you
              save, the AI summaries we generate for them, and basic usage
              counts.
            </li>
            <li>
              We don’t sell your data, we don’t train AI on it, and we don’t
              read your links ourselves.
            </li>
            <li>
              To make summaries, we send the page content to Cloudflare’s
              Workers AI service (running Meta’s Llama 3.3 model). It runs on
              Cloudflare infrastructure — the content doesn’t leave Cloudflare
              for this step. The Pro chat feature is different: it goes through
              OpenRouter to Google Gemini.
            </li>
            <li>
              You can export everything and delete your account at any time.
              Delete means delete.
            </li>
            <li>
              If you live in the EU/UK or California, you have specific legal
              rights — see “Your rights” below.
            </li>
          </ul>
        </section>

        <section id="who-we-are">
          <h2>Who we are</h2>
          <p>
            Cloudstash is operated by Phantom Edtech LLC, a Wyoming limited
            liability company:
          </p>
          <LegalAddress />
          <p>We’re the data controller for the information described here.</p>
        </section>

        <section id="what-we-collect">
          <h2>What we collect</h2>
          <p>
            <strong>Account information.</strong> When you sign in with Google,
            we receive your email address, your name, and your Google account
            ID. We don’t get access to your Gmail, Drive, Calendar, or anything
            else in your Google account.
          </p>
          <p>
            <strong>The links you save.</strong> The URL, the page title and
            metadata, any tags you add, the AI-generated summary, and
            timestamps. If you save through Telegram, Raycast, the iOS Shortcut,
            the Chrome extension, or X bookmarks, the link arrives the same way.
          </p>
          <p>
            <strong>Content fetched from links.</strong> When you save a link,
            our server fetches the page so we can extract the title, a
            description, and the text we send to the AI for summarization. The
            summary itself is generated on Cloudflare Workers AI — content for
            summaries doesn’t leave Cloudflare infrastructure. We don’t store
            the full page — only what’s needed for the summary and a small
            metadata snapshot.
          </p>
          <p>
            <strong>Usage information.</strong> Cloudflare Analytics Engine
            records counts of in-app events tied to your user ID (for example,
            how many links you’ve saved this month) so we can enforce plan
            limits and understand what’s used.
          </p>
          <p>
            <strong>Technical information.</strong> Standard server logs (IP
            address, user agent, timestamps) generated by Cloudflare. These are
            short-lived and used for security, abuse prevention, and debugging.
          </p>
          <p>
            <strong>Analytics scripts.</strong> Every page on cloudstash.dev
            currently loads two scripts in the browser: Meta Pixel (a Facebook
            tracking script used to measure ads) and OneDollarStats (a
            lightweight page-view counter we use to see traffic). Both run on
            the public pages and inside the signed-in app. They record that a
            browser visited a page; they don’t see the contents of your archive.
            We’re working to scope Meta Pixel to the marketing pages only —
            until then, treat the app as if a third-party page-view counter is
            watching, because one is.
          </p>
        </section>

        <section id="what-we-dont-collect">
          <h2>What we don’t collect</h2>
          <ul>
            <li>We don’t read your links manually.</li>
            <li>We don’t sell your data.</li>
            <li>
              We don’t use your links, summaries, or chats to train any AI model
              — ours or anyone else’s.
            </li>
            <li>
              We don’t take your payment card details ourselves — those go
              straight to Stripe (see “Who we share data with” below).
            </li>
            <li>
              We don’t share data with advertisers other than the Meta Pixel
              page-visit signal described above.
            </li>
          </ul>
        </section>

        <section id="legal-bases">
          <h2>Why we collect it (legal bases under GDPR)</h2>
          <p>
            If you’re in the EU, UK, or Switzerland, we rely on these legal
            bases:
          </p>
          <ul>
            <li>
              <strong>Performance of a contract</strong> — we need your account
              and your saved links to actually run the service.
            </li>
            <li>
              <strong>Legitimate interests</strong> — protecting against abuse,
              improving the product in aggregate, measuring marketing.
            </li>
            <li>
              <strong>Consent</strong> — where we ask for it (for example,
              optional emails).
            </li>
            <li>
              <strong>Legal obligation</strong> — when the law requires us to
              keep or share information.
            </li>
          </ul>
        </section>

        <section id="sub-processors">
          <h2>Who we share data with</h2>
          <p>
            We use a small number of vendors (“sub-processors”) to run the
            service. We share only what each one needs:
          </p>
          <ul>
            <li>
              <strong>Cloudflare, Inc.</strong> — hosting, database, storage,
              edge cache, and the Workers AI service that generates your link
              summaries. Everything you store with us is on Cloudflare
              infrastructure.
            </li>
            <li>
              <strong>Google LLC (Sign in with Google)</strong> — the OAuth
              handshake when you sign in. We receive your email, name, and
              Google user ID.
            </li>
            <li>
              <strong>OpenRouter, Inc.</strong> — used only for the Pro
              chat-with-your-archive feature. If you’re on Pro and you chat with
              your archive, your messages are routed through OpenRouter. Free
              and Plus users never hit OpenRouter.
            </li>
            <li>
              <strong>Google LLC (Gemini)</strong> — the AI model behind the Pro
              chat feature, reached through OpenRouter. Free and Plus summaries
              don’t go through Gemini.
            </li>
            <li>
              <strong>Stripe, Inc.</strong> — subscription billing. Your card
              details go directly to Stripe and are never seen or stored by
              Cloudstash. We share your email, name, and billing details when
              you subscribe.
            </li>
            <li>
              <strong>Telegram FZ-LLC</strong> — only if you connect the
              Cloudstash Telegram bot. It receives the messages you send to the
              bot.
            </li>
            <li>
              <strong>Meta Platforms, Inc.</strong> — Meta Pixel for ad
              measurement. It currently fires on every page on cloudstash.dev,
              including pages inside the signed-in app. It receives the fact
              that a browser visited a URL on our domain; it does not see your
              archive contents.
            </li>
            <li>
              <strong>OneDollarStats</strong> — a lightweight page-view counter
              that runs on every page. It records anonymous visit counts so we
              can see traffic without running a heavy analytics product.
            </li>
          </ul>
          <p>
            Where required, we sign Data Processing Agreements with these
            vendors. We update this list when we change vendors — material
            changes are announced via email.
          </p>
          <p>
            We don’t share your data with anyone else except (a) when you tell
            us to, (b) when required by law, or (c) if Cloudstash is acquired
            (we’ll tell you before this happens and you’ll be able to delete
            your account first).
          </p>
        </section>

        <section id="where-it-lives">
          <h2>Where your data lives</h2>
          <p>
            Cloudflare runs Cloudstash on its global network. Your data is
            stored primarily in the United States, with caches served from the
            Cloudflare edge location closest to you. When data leaves the EU/UK,
            we rely on Standard Contractual Clauses with our vendors.
          </p>
        </section>

        <section id="retention">
          <h2>How long we keep it</h2>
          <p>
            We keep your account and saved links for as long as your account is
            open.
          </p>
          <p>When you delete your account (Settings → Account → Delete), we:</p>
          <ol>
            <li>
              Wipe your archive — links, summaries, tags, chat history —
              promptly (typically within minutes; longer only if a step has to
              retry).
            </li>
            <li>
              Remove your account record within 30 days, including any backups
              still in rotation.
            </li>
          </ol>
          <p>
            Server logs from Cloudflare typically roll off within 30 days.
            Aggregated, anonymous usage counts may be kept for analytics.
          </p>
        </section>

        <section id="cookies">
          <h2>Cookies and similar storage</h2>
          <p>
            We use the minimum cookies and local storage needed to keep you
            signed in, remember your preferences, and run features like offline
            sync. Meta Pixel and OneDollarStats set their own cookies in your
            browser when they run, on both marketing and in-app pages.
          </p>
          <p>
            We don’t respond to the legacy “Do Not Track” browser signal — no
            major service does, and the spec was never finalized. Use the in-app
            controls and Settings → Account → Delete to control your data
            instead. If you’re a California resident, you can also use the
            Global Privacy Control browser signal — we treat it as a valid
            opt-out request under California law.
          </p>
        </section>

        <section id="your-rights">
          <h2>Your rights</h2>
          <p>
            <strong>If you live in the EU, UK, or Switzerland</strong>, you have
            the right to:
          </p>
          <ul>
            <li>Access the data we hold about you.</li>
            <li>Correct it if it’s wrong.</li>
            <li>Delete your account and the data tied to it.</li>
            <li>
              Receive a copy in a portable format (we have an Export button
              in-app).
            </li>
            <li>Restrict or object to how we process it.</li>
            <li>
              Withdraw consent at any time (for the parts where we relied on
              consent).
            </li>
            <li>Complain to your local Data Protection Authority.</li>
          </ul>
          <p>
            <strong>If you live in California</strong>, you have the right to:
          </p>
          <ul>
            <li>
              Know what personal information we collect, why, and who we share
              it with.
            </li>
            <li>Request a copy of that information.</li>
            <li>Delete it.</li>
            <li>Not be discriminated against for exercising your rights.</li>
          </ul>
          <p>
            We don’t sell personal information for money. Meta Pixel page-view
            data may be considered a “share” for cross-context behavioral
            advertising under California law — if you’re a California resident
            and you don’t want this, email{" "}
            <a href="mailto:support@cloudstash.dev">support@cloudstash.dev</a>{" "}
            or send a Global Privacy Control signal and we’ll treat that as your
            opt-out.
          </p>
          <p>
            <strong>
              If you live in Virginia, Colorado, Connecticut, Utah, Texas, or
              another US state with a consumer privacy law
            </strong>
            , you have similar rights — typically access, correction, deletion,
            portability, and the right to opt out of targeted advertising or
            “sales.” Use the same support email to exercise them.
          </p>
          <p>
            To exercise any of these rights, email{" "}
            <a href="mailto:support@cloudstash.dev">support@cloudstash.dev</a>.
            We’ll verify your identity and respond within 30 days (up to 45 days
            for California, extendable once if the law allows).
          </p>
        </section>

        <section id="children">
          <h2>Children</h2>
          <p>
            Cloudstash is not for children under 13, and we don’t knowingly
            collect data from them. If you’re in the EU, you must be at least 16
            to use Cloudstash unless your country has set a lower age (we follow
            your country’s age of consent for data processing).
          </p>
        </section>

        <section id="security">
          <h2>Security</h2>
          <p>
            We host on Cloudflare, which encrypts data in transit and at rest.
            We use short-lived access tokens, scoped database queries, and
            follow standard security practices. No system is perfect — if we
            ever have a breach that affects you, we’ll notify you without
            unreasonable delay, and within 72 hours where the law requires it.
          </p>
        </section>

        <section id="changes">
          <h2>Changes</h2>
          <p>
            If we change this policy in a way that materially affects your
            rights, we’ll email you and post a notice in-app. Otherwise we’ll
            just update the date at the top.
          </p>
        </section>

        <section id="contact">
          <h2>Contact</h2>
          <LegalAddress />
        </section>
      </LegalArticle>
    </LegalShell>
  );
}
