/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectTelegramRouteImport } from './routes/connect/telegram'
import { Route as ConnectRaycastRouteImport } from './routes/connect/raycast'
import { Route as AuthedInboxRouteImport } from './routes/_authed/inbox'
import { Route as AuthedCompletedRouteImport } from './routes/_authed/completed'
import { Route as AuthedBrandRouteImport } from './routes/_authed/brand'
import { Route as AuthedArchiveRouteImport } from './routes/_authed/archive'
import { Route as AuthedAllRouteImport } from './routes/_authed/all'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectTelegramRoute = ConnectTelegramRouteImport.update({
  id: '/connect/telegram',
  path: '/connect/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRaycastRoute = ConnectRaycastRouteImport.update({
  id: '/connect/raycast',
  path: '/connect/raycast',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInboxRoute = AuthedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompletedRoute = AuthedCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBrandRoute = AuthedBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedArchiveRoute = AuthedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAllRoute = AuthedAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/all': typeof AuthedAllRoute
  '/archive': typeof AuthedArchiveRoute
  '/brand': typeof AuthedBrandRoute
  '/completed': typeof AuthedCompletedRoute
  '/inbox': typeof AuthedInboxRoute
  '/connect/raycast': typeof ConnectRaycastRoute
  '/connect/telegram': typeof ConnectTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/all': typeof AuthedAllRoute
  '/archive': typeof AuthedArchiveRoute
  '/brand': typeof AuthedBrandRoute
  '/completed': typeof AuthedCompletedRoute
  '/inbox': typeof AuthedInboxRoute
  '/connect/raycast': typeof ConnectRaycastRoute
  '/connect/telegram': typeof ConnectTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/all': typeof AuthedAllRoute
  '/_authed/archive': typeof AuthedArchiveRoute
  '/_authed/brand': typeof AuthedBrandRoute
  '/_authed/completed': typeof AuthedCompletedRoute
  '/_authed/inbox': typeof AuthedInboxRoute
  '/connect/raycast': typeof ConnectRaycastRoute
  '/connect/telegram': typeof ConnectTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/all'
    | '/archive'
    | '/brand'
    | '/completed'
    | '/inbox'
    | '/connect/raycast'
    | '/connect/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/all'
    | '/archive'
    | '/brand'
    | '/completed'
    | '/inbox'
    | '/connect/raycast'
    | '/connect/telegram'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authed/all'
    | '/_authed/archive'
    | '/_authed/brand'
    | '/_authed/completed'
    | '/_authed/inbox'
    | '/connect/raycast'
    | '/connect/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ConnectRaycastRoute: typeof ConnectRaycastRoute
  ConnectTelegramRoute: typeof ConnectTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/telegram': {
      id: '/connect/telegram'
      path: '/connect/telegram'
      fullPath: '/connect/telegram'
      preLoaderRoute: typeof ConnectTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/raycast': {
      id: '/connect/raycast'
      path: '/connect/raycast'
      fullPath: '/connect/raycast'
      preLoaderRoute: typeof ConnectRaycastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/inbox': {
      id: '/_authed/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedInboxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/completed': {
      id: '/_authed/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof AuthedCompletedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/brand': {
      id: '/_authed/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AuthedBrandRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/archive': {
      id: '/_authed/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthedArchiveRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/all': {
      id: '/_authed/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AuthedAllRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAllRoute: typeof AuthedAllRoute
  AuthedArchiveRoute: typeof AuthedArchiveRoute
  AuthedBrandRoute: typeof AuthedBrandRoute
  AuthedCompletedRoute: typeof AuthedCompletedRoute
  AuthedInboxRoute: typeof AuthedInboxRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAllRoute: AuthedAllRoute,
  AuthedArchiveRoute: AuthedArchiveRoute,
  AuthedBrandRoute: AuthedBrandRoute,
  AuthedCompletedRoute: AuthedCompletedRoute,
  AuthedInboxRoute: AuthedInboxRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ConnectRaycastRoute: ConnectRaycastRoute,
  ConnectTelegramRoute: ConnectTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
