/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTrashRouteImport } from './routes/_authed/trash'
import { Route as AuthedCompletedRouteImport } from './routes/_authed/completed'
import { Route as AuthedAllRouteImport } from './routes/_authed/all'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrashRoute = AuthedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompletedRoute = AuthedCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAllRoute = AuthedAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/all': typeof AuthedAllRoute
  '/completed': typeof AuthedCompletedRoute
  '/trash': typeof AuthedTrashRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/all': typeof AuthedAllRoute
  '/completed': typeof AuthedCompletedRoute
  '/trash': typeof AuthedTrashRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/all': typeof AuthedAllRoute
  '/_authed/completed': typeof AuthedCompletedRoute
  '/_authed/trash': typeof AuthedTrashRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/all' | '/completed' | '/trash'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/all' | '/completed' | '/trash' | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/all'
    | '/_authed/completed'
    | '/_authed/trash'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trash': {
      id: '/_authed/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthedTrashRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/completed': {
      id: '/_authed/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof AuthedCompletedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/all': {
      id: '/_authed/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AuthedAllRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAllRoute: typeof AuthedAllRoute
  AuthedCompletedRoute: typeof AuthedCompletedRoute
  AuthedTrashRoute: typeof AuthedTrashRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAllRoute: AuthedAllRoute,
  AuthedCompletedRoute: AuthedCompletedRoute,
  AuthedTrashRoute: AuthedTrashRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
